[package]
name = "aoc_helper"
version = "0.2.0"
edition = "2021"

[dependencies]
ureq = { version = "2.3.1", features = ["charset"] }
criterion = "0.5.1"
colored = "2.0.0"
anyhow = "1.0.50"
dotenvy = "0.15.6"

[dev-dependencies]
indoc = "2.0.4"
itertools = "0.12.0"
